### PR TITLE
Deployment restructure

### PR DESCRIPTION
**Pull request by thehonker**
This PR:
- Pulls config out of public_html
- Sets up Dockerfiles for nginx and php-fpm
- Sets up compose stack for prod and dev

### CODE REVIEW

**Review by itsrachelfish — CHANGES_REQUESTED** [review]
This mostly worked, but it looks like we need to include that same SQL_MODE fix?

image

**Review by itsrachelfish — CHANGES_REQUESTED** [review]
Edit: Oops, this was supposed to be review for the wiki - https://github.com/wetfish/wiki/pull/15#pullrequestreview-1332150488

**Comment by itsrachelfish** [comment]
> This mostly worked, but it looks like we need to include that same SQL_MODE fix?

Tested again with the most recent changes. This issue is still present @g-o-o-s

**Comment by thehonker** [comment]
> Tested again with the most recent changes. This issue is still present @g-o-o-s

Reworked a bunch in f9a9ebd making things similar to other projects. Try it with those changes, it work in my env now.

**Review by itsrachelfish — CHANGES_REQUESTED** [review]
Oops. Left review on the wrong PR again :sweat_smile:

https://github.com/wetfish/wiki/pull/15#pullrequestreview-1473011264

**Review by itsrachelfish — APPROVED** [review]
Tested locally, working as expected :tada:

**Pull request merged**
